### ISSUE TITLE
Unable to activate tdx-0.2.9, because slop-4.6.1 conflicts with slop (~> 4.4.1)

### ISSUE THREAD

**Issue by php-coder** [yegor256/tdx#13]
I'm trying to use `tdx` but it fails right after start:
```console
$ tdx 
/usr/share/rubygems/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate tdx-0.2.9, because slop-4.6.1 conflicts with slop (~> 4.4.1) (Gem::ConflictError)
	from /usr/share/rubygems/rubygems/specification.rb:1408:in `activate'
	from /usr/share/rubygems/rubygems.rb:196:in `rescue in try_activate'
	from /usr/share/rubygems/rubygems.rb:193:in `try_activate'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/coder/.gem/ruby/gems/tdx-0.2.9/bin/tdx:27:in `<top (required)>'
	from /home/coder/bin/tdx:22:in `load'
	from /home/coder/bin/tdx:22:in `<main>'
$ gem list | grep slop
slop (4.6.1, 4.4.3, 3.6.0)
```
Despite the fact that I don't know how to resolve such a conflict, I think that this report can be interesting to developers so they can update `tdx` dependencies to use a newer `slop` version.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder thanks for reporting. Would you be interested in contributing with a pull request?

**Comment by php-coder** [comment]
> Would you be interested in contributing with a pull request?

@yegor256 No, I wouldn't, thank you.
